# Generated by Django 5.2.8 on 2025-11-27 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=20)),
                ('max_score', models.IntegerField(default=100)),
                ('time_limit_ms', models.IntegerField(default=1000)),
                ('memory_limit_kb', models.IntegerField(default=65536)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contests.contest')),
            ],
            options={
                'unique_together': {('contest', 'code')},
            },
        ),
    ]
