# Generated by Django 5.2.8 on 2025-11-27 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coders', '0001_initial'),
        ('contests', '0001_initial'),
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=50)),
                ('code', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('wrong_answer', 'Wrong Answer'), ('runtime_error', 'Runtime Error'), ('time_limit', 'Time Limit Exceeded'), ('compilation_error', 'Compilation Error'), ('partial', 'Partial Score')], default='pending')),
                ('score', models.IntegerField(default=0)),
                ('attempt_no', models.IntegerField(default=1)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('judged_at', models.DateTimeField(blank=True, null=True)),
                ('coder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='coders.coder')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contests.contest')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='problems.problem')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
