# Generated by Django 5.2.8 on 2025-11-27 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=120, unique=True)),
                ('country', models.CharField(max_length=50)),
                ('bio', models.TextField(blank=True, null=True)),
                ('rating', models.IntegerField(default=1500)),
                ('points_total', models.IntegerField(default=0)),
                ('total_submissions', models.IntegerField(default=0)),
                ('accepted_submissions', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
